# Scipy

### 1. numpy에서 특수행렬을 만드는 함수

In [2]:
import numpy as np

#### 1) ones()

In [25]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### 2) zeros()

In [27]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [28]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 3) eye(N=, M=, K=, dtype=): 항등행렬

- N: 행의 수, M: 열의 수, K: 대각의 위치, dtype: 값의 타입

In [29]:
np.eye(3, dtype=int) # 기본적으로 eye()는 정방행렬(행과 열의 수가 같음)을 생성

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [30]:
np.eye(4, k=1, dtype=int)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [44]:
np.eye(5, k=-1, dtype=int)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

#### 4) diag(): 정방행렬에서 대각요소만 추출하여 벡터를 만듦

In [35]:
x = np.eye(5, dtype=int)
x

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [36]:
np.diag(x)

array([1, 1, 1, 1, 1])

In [39]:
x1 = np.arange(9).reshape(3,3)
x1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
np.diag(x1)

array([0, 4, 8])

In [41]:
np.diag(x1, k=1) # 대각의 위치를 지정하여 값 추출

array([1, 5])

In [42]:
np.diag(x1, k=-1)

array([3, 7])

- diag() 벡터요소를 대각 요소로 하는 정방행렬을 만듦

In [43]:
np.diag(np.diag(x1))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

### 2. Scipy에서 사용하는 희소행렬

- 가장 중요한 기능: scipy.sparse
    - scikit-learn에서 데이터를 표현하는 하나의 방법인 희소 행렬 기능을 제공
    - 희소행렬(Sparse Matrix): 0을 많이 포함하고 있는 행렬

In [45]:
import numpy as np
from scipy import sparse

In [47]:
b1 = np.eye(4, dtype=int)
b1

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

#### 1) CSR(Compressed Row Storage) 포맷

- 행의 인덱스를 압축해서 저장
- sparse.csr_matrix(): 0이 아닌 원소만 저장

In [52]:
# numpy 배열을 CSR 포맷의 scipy 희소행렬로 변환
sparse_matrix = sparse.csr_matrix(b1)
print("scipy csr matrix: \n{}".format(sparse_matrix))

scipy csr matrix: 
  (0, 0)	1
  (1, 1)	1
  (2, 2)	1
  (3, 3)	1


In [51]:
b2 = np.eye(5, k=-1, dtype=int)
b2

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [77]:
sparse_matrix = sparse.csr_matrix(b2)
print("scipy csr matrix: \n{}".format(sparse_matrix))

scipy csr matrix: 
  (1, 0)	1
  (2, 1)	1
  (3, 2)	1
  (4, 3)	1


In [78]:
b3 = np.arange(16).reshape(4,4)
b3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [79]:
np.diag(b3)

array([ 0,  5, 10, 15])

In [80]:
x = np.diag(np.diag(b3))
x

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [81]:
sparse_matrix = sparse.csr_matrix(x)
print("scipy csr matrix: \n{}".format(sparse_matrix))

scipy csr matrix: 
  (1, 1)	5
  (2, 2)	10
  (3, 3)	15


#### 2) COO(Coordinate) 포맷

- 희소행렬을 직접 만드는 방법, 데이터가 놓일 행렬의 위치를 별도의 매개변수로 전달
    - 메모리 부족현상 방지

In [82]:
data = np.ones(4)
data

array([1., 1., 1., 1.])

In [83]:
row_indices = np.arange(4)
col_indices = np.arange(4)

In [84]:
# 희소행렬을 직접 만드는 방법
eye_coo = sparse.coo_matrix((data, (row_indices, col_indices)))
print("coo matrix: \n{}".format(eye_coo))

coo matrix: 
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
